# Generated by Django 2.2.3 on 2019-07-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('title_en', models.CharField(max_length=200, verbose_name='английское название')),
                ('title_jp', models.CharField(max_length=200, verbose_name='японское название')),
                ('description', models.TextField(max_length=2000, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemons', verbose_name='изображение')),
                ('next_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_evolution', to='pokemon_entities.Pokemon', verbose_name='в кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='появится')),
                ('disappeared_at', models.DateTimeField(verbose_name='исчезнет')),
                ('level', models.IntegerField(verbose_name='уровень')),
                ('health', models.IntegerField(verbose_name='здоровье')),
                ('strength', models.IntegerField(verbose_name='прочность')),
                ('defence', models.IntegerField(verbose_name='защита')),
                ('stamina', models.IntegerField(verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='покемон')),
            ],
        ),
    ]
